### ISSUE TITLE
`classId` of the `MsgIssue` response of x/token has `\"` each end of string

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#463] opened 2022-03-16 00:57 UTC
## Summary of Bug

`classId` of the `MsgIssue` response of x/token has `\"` each end of string

For example, if the real response of `classId` is `ca8bfd79`, the response is `\"ca8bfd79\"`.
```json
"events": [
          {
            "type": "lbm.token.v1.EventIssue",
            "attributes": [
              {
                "key": "class_id",
                "value": "\"ca8bfd79\""
              }
            ]
          },
```

## Version

lbm-sdk v0.45.0-rc0

## Steps to Reproduce

1. request `MsgIssue` of x/token 
2. parsing the response.

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by 0Tech** [comment] 2022-03-18 04:23
I confirmed the upstream (cosmos-sdk) behaves exactly in the same way as the description here. It is not limited to x/token, but the all events using protobuf.
So I think it's not a bug, or at least not a bug only in our sdk.
We can discuss about it, and decide whether we should fix it and push the fix to the upstream.

**Comment by 0Tech** [comment] 2022-04-11 04:28
We concluded this is not a bug, after the discussion with @zemyblue.
You may re-open the issue if you think this should be fixed.

**Closed by 0Tech** 2022-04-11 04:28 UTC
Labels: bug
