### ISSUE TITLE
default output method was changed to 'text' from 'json'

### ISSUE THREAD

**Issue by brew0722** [line/lbm-sdk#473] opened 2022-03-22 10:17 UTC
## Summary of Bug

As shown below, in the past, the default output method was json.
`  -o, --output string            Output format (text|json) (default "json")`
The cli still tells me that the default is json.

However, the result output is text by default now.

The defaults below appear to have been changed.
https://github.com/line/lbm-sdk/blob/393d1fcd3f3aaf2c632eff74d21d380d70e60a96/client/config/config.go#L15

## Version

lbm v0.3.0-rc0
lbm-sdk v0.45.0-rc0

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by 0Tech** [comment] 2022-03-23 01:57
If you don't mind, can you describe your expectation more specifically?

e.g.)
On queries: text
On transactions: json

The example above is the result produced on my local machine.
And I assumed that there is a typo on the version you specified, so I tested it on version 0.43.0-rc0.

**Comment by brew0722** [comment] 2022-03-23 02:07
@0Tech 
On queries: json
On transactions: json

I'll add an example.
As far as I know, this is common to all response outputs of lbm.


Below is the default output.
> user@AL01696733 sample-token % lbm tx wasm store target/wasm32-unknown-unknown/release/sample_token.wasm  --from alice --keyring-backend test --chain-id lbm --gas 1000000 -b block -y
> 
> code: 0
> codespace: ""
> data: 0A100A0A73746F72652D636F646512020809
> events:
> - attributes:
>   - index: true
>     key: YWNjX3NlcQ==
>     value: bGluazF0d3NmbXVqMjhuZHBoNTRrNG53OGNyd3U4aDljOG1oM3J0eDcwNS84
>   type: tx
> - attributes:
>   - index: true
>     key: c2lnbmF0dXJl
>     value: NUpJSmxiUkpCV1FoK3FhcXlCd2Z0Ly9rQjZNS09wNWRXcWZhRFdzTzZuMXN3MWx0eG5TZDlYR2l5OWJRdjBmVk9obFJBOGtSV0hReTA2Q21mT3JZUXc9PQ==
>   type: tx
> - attributes:
>   - index: true
>     key: YWN0aW9u
>     value: c3RvcmUtY29kZQ==
>   type: message
> - attributes:
>   - index: true
>     key: bW9kdWxl
>     value: d2FzbQ==
>   - index: true
>     key: c2VuZGVy
>     value: bGluazF0d3NmbXVqMjhuZHBoNTRrNG53OGNyd3U4aDljOG1oM3J0eDcwNQ==
>   type: message
> - attributes:
>   - index: true
>     key: Y29kZV9pZA==
>     value: OQ==
>   type: store_code
> gas_used: "935914"
> gas_wanted: "1000000"
> height: "6717"
> info: ""
> logs:
> - events:
>   - attributes:
>     - key: action
>       value: store-code
>     - key: module
>       value: wasm
>     - key: sender
>       value: link1twsfmuj28ndph54k4nw8crwu8h9c8mh3rtx705
>     type: message
>   - attributes:
>     - key: code_id
>       value: "9"
>     type: store_code
>   log: ""
>   msg_index: 0
> raw_log: '[{"events":[{"type":"message","attributes":[{"key":"action","value":"store-code"},{"key":"module","value":"wasm"},{"key":"sender","value":"link1twsfmuj28ndph54k4nw8crwu8h9c8mh3rtx705"}]},{"type":"store_code","attributes":[{"key":"code_id","value":"9"}]}]}]'
> timestamp: ""
> tx: null
> txhash: 8D42E9AE0FA3B00D361551B766B42FE35B95CAB15A39A79E0DE7623E493503E6

and below is the json output(using `-o json`)

> user@AL01696733 sample-token % lbm tx wasm store target/wasm32-unknown-unknown/release/sample_token.wasm  --from alice --keyring-backend test --chain-id lbm --gas 1000000 -b block -o json -y
> 
> {"height":"6737","txhash":"B0FB63BA41F4EA2E69B35662BAAC99D360F3343B07B21AC93B928241DFAE1ABD","codespace":"","code":0,"data":"0A100A0A73746F72652D636F64651202080A","raw_log":"[{\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"store-code\"},{\"key\":\"module\",\"value\":\"wasm\"},{\"key\":\"sender\",\"value\":\"link1twsfmuj28ndph54k4nw8crwu8h9c8mh3rtx705\"}]},{\"type\":\"store_code\",\"attributes\":[{\"key\":\"code_id\",\"value\":\"10\"}]}]}]","logs":[{"msg_index":0,"log":"","events":[{"type":"message","attributes":[{"key":"action","value":"store-code"},{"key":"module","value":"wasm"},{"key":"sender","value":"link1twsfmuj28ndph54k4nw8crwu8h9c8mh3rtx705"}]},{"type":"store_code","attributes":[{"key":"code_id","value":"10"}]}]}],"info":"","gas_wanted":"1000000","gas_used":"935914","tx":null,"timestamp":"","events":[{"type":"tx","attributes":[{"key":"YWNjX3NlcQ==","value":"bGluazF0d3NmbXVqMjhuZHBoNTRrNG53OGNyd3U4aDljOG1oM3J0eDcwNS85","index":true}]},{"type":"tx","attributes":[{"key":"c2lnbmF0dXJl","value":"d2xpYmU3UXZUL0I0d005Y1FCdW80MU54bFhjVXBURVBPa0VZZGQ2OUN1MDlMbSt1Z1ZHako3VzFSb3crSUFYMXcvZUtCUlQramdsVnJUZ2JJME9kaFE9PQ==","index":true}]},{"type":"message","attributes":[{"key":"YWN0aW9u","value":"c3RvcmUtY29kZQ==","index":true}]},{"type":"message","attributes":[{"key":"bW9kdWxl","value":"d2FzbQ==","index":true},{"key":"c2VuZGVy","value":"bGluazF0d3NmbXVqMjhuZHBoNTRrNG53OGNyd3U4aDljOG1oM3J0eDcwNQ==","index":true}]},{"type":"store_code","attributes":[{"key":"Y29kZV9pZA==","value":"MTA=","index":true}]}]}

**Comment by 0Tech** [comment] 2022-03-23 06:54
Confirmed it is reproducible. And the recent cosmos-sdk shows the same behavior.
We'd better report it to cosmos-sdk.

**Comment by 0Tech** [comment] 2022-03-23 06:58
Besides, it seems they prefer yaml format.
cosmos/cosmos-sdk#7978
Still, it's a bug because the cli prints the default output is in json, as you mentioned.

**Comment by 0Tech** [comment] 2022-03-23 07:41
I concluded it is not a bug, let me explain.
cosmos/cosmos-sdk#8953 introduces client config, which has the default output format inside it. And we bumped up so we have the changes too.
The config file overrides default behavior of the client binary, so it's OK to say that the default output format of tx is json.

Sorry for the confusion.

**Comment by 0Tech** [comment] 2022-03-23 07:43
If you agree with my opinion, feel free to close the issue, or we may continue discussion on the subject.

**Comment by brew0722** [comment] 2022-03-23 07:46
> If you agree with my opinion, feel free to close the issue, or we may continue discussion on the subject.

I agree that the 'text' format is more appropriate by default.
It seems that you only need to change the default guide in the cli help below.
`-o, --output string Output format (text|json) (default "json")`

**Comment by 0Tech** [comment] 2022-03-23 07:48
> It seems that we only need to change the default guide in the cli help below.

I think it's OK to print it as is, because the default of the "binary" is always json. Please refer to:

> The config file overrides default behavior of the client binary, so it's OK to say that the default output format of tx is json.
> And because they prefer yaml format, they decided to put "text" to the config file.

**Comment by brew0722** [comment] 2022-03-23 07:52
Oh, I understood the meaning above.
This is the result of overwriting by `client.toml`.

However, I think users may be a little confused.
It's definitely not a bug, but I think it would be more appropriate to match the default output of client.toml and the default output of binary to match the initial behavior.

**Comment by 0Tech** [comment] 2022-03-23 08:01
> However, I think users may be a little confused.

I strongly agree on it. If users have any idea about the config file, they may think this is a bug as we did.

**Comment by 0Tech** [comment] 2022-03-24 01:38
How about changing the default value in the config?
If we provide the empty string (""), it would not override the default value of the binary.
I've tested it and confirmed it working as expected.

If you think it's OK to go, I will submit a PR of it.

**Comment by brew0722** [comment] 2022-03-24 04:35
> If we provide the empty string (""), it would not override the default value of the binary.

I agree with your suggestion.
At first I cared about the empty string, but I know that by default the chain-id is also empty generated.
I think it would be good to explain that well in the existing comment in config.toml.

> # CLI output format (text|json)

**Closed** 2022-03-29 02:16 UTC
